# Generated by Django 4.0 on 2022-01-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=30)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('entrega', models.BooleanField(default=False)),
                ('obs', models.TextField(blank=True, null=True)),
                ('data', models.DateField(auto_now_add=True)),
                ('lanche', models.CharField(choices=[('----', '----'), ('X-Salada', 'X-Salada'), ('X-Duplo Salada', 'X-Duplo Salada'), ('X-Burger', 'X-Burger'), ('Frango', 'X-Frango'), ('X-Frango Bacon', 'X-Frango Bacon'), ('X-Frango Egg', 'X-Frango Egg'), ('X-Frango Bacon Egg', 'X-Frango Bacon Egg'), ('X-Egg', 'X-Egg'), ('X-Bacon', 'X-Bacon'), ('X-Bacon Egg', 'X-Bacon Egg'), ('Hot Dog', 'Hot Dog'), ('Dog Egg', 'Dog Egg'), ('Dog Bacon', 'Dog Bacon'), ('Dog Bacon Egg', 'Dog Bacon Egg'), ('X-Dogão', 'X-Dogão'), ('X-Calabresa', 'X-Calabresa'), ('X-Tudo', 'X-Tudo')], default='----', max_length=20)),
                ('alface', models.BooleanField(default=True)),
                ('tomate', models.BooleanField(default=True)),
                ('maionese', models.BooleanField(default=True)),
                ('hellmanns', models.BooleanField(default=False)),
                ('pure', models.BooleanField(default=True)),
                ('milho', models.BooleanField(default=True)),
                ('anel', models.BooleanField(default=False, verbose_name='Anel de Cebola')),
                ('catupiry', models.BooleanField(default=False)),
                ('quant_lanche', models.IntegerField(blank=True, null=True)),
                ('total_lanche', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço')),
                ('adicional_maionese', models.BooleanField(default=False, verbose_name='Adicional de Maionese')),
                ('bebida', models.CharField(choices=[('----', '----'), ('Refrigerante Lata', 'Refrigerante Lata'), ('Refrigerante 600', 'Refrigerante 600'), ('Refrigerante 1,5L', 'Refrigerante 1,5L'), ('Suco com água', 'Suco com água'), ('Suco com leite', 'Suco com leite')], default='----', max_length=20)),
                ('quant_bebida', models.IntegerField(blank=True, null=True)),
                ('total_bebida', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('porcao', models.CharField(choices=[('----', '----'), ('Batata Meia', 'Batata Meia'), ('Batata Inteira', 'Batata Inteira'), ('Anel de Cebola', 'Anel de Cebola'), ('Frango', 'Fango'), ('Mini fritas', 'Mini fritas'), ('Especial', 'Especial')], default='----', max_length=20, verbose_name='Porção')),
                ('bacon', models.BooleanField(default=False)),
                ('cheddar', models.BooleanField(default=False)),
                ('quant_pocao', models.IntegerField(blank=True, null=True)),
                ('total_porcao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('acai', models.CharField(choices=[('----', '----'), ('400ml', '400ml'), ('500ml', '500ml'), ('700ml', '700ml')], default='----', max_length=30, verbose_name='Açaí')),
                ('quant_acai', models.IntegerField(blank=True, null=True)),
                ('total_acai', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
    ]
