# Generated by Django 4.0 on 2022-01-04 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='acai',
            new_name='l1_acai',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='adicional_maionese',
            new_name='l1_adicional_maionese',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='bebida',
            new_name='l1_bebida',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='lanche',
            new_name='l1_lanche',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='porcao',
            new_name='l1_porcao',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='quant_acai',
            new_name='l1_quant_acai',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='quant_bebida',
            new_name='l1_quant_bebida',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='quant_lanche',
            new_name='l1_quant_lanche',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='quant_pocao',
            new_name='l1_quant_pocao',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='total_acai',
            new_name='l1_total_acai',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='total_bebida',
            new_name='l1_total_bebida',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='total_lanche',
            new_name='l1_total_lanche',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='total_porcao',
            new_name='l1_total_porcao',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='alface',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='anel',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='bacon',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='catupiry',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cheddar',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='hellmanns',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='maionese',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='milho',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='pure',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='tomate',
        ),
        migrations.AddField(
            model_name='pedido',
            name='l10_acai',
            field=models.CharField(choices=[('----', '----'), ('400ml', '400ml'), ('500ml', '500ml'), ('700ml', '700ml')], default='----', max_length=30, verbose_name='Açaí'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l10_adicional_maionese',
            field=models.BooleanField(default=False, verbose_name='Adicional de Maionese'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l10_alface',
            field=models.BooleanField(default=False, verbose_name='s/ Alface'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l10_anel',
            field=models.BooleanField(default=False, verbose_name='c/ Anel de Cebola'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l10_bacon',
            field=models.BooleanField(default=False, verbose_name='c/ Bacon'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l10_bebida',
            field=models.CharField(choices=[('----', '----'), ('Refrigerante Lata', 'Refrigerante Lata'), ('Refrigerante 600', 'Refrigerante 600'), ('Refrigerante 1,5L', 'Refrigerante 1,5L'), ('Suco com água', 'Suco com água'), ('Suco com leite', 'Suco com leite')], default='----', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l10_catupiry',
            field=models.BooleanField(default=False, verbose_name='c/ Catupiry'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l10_cheddar',
            field=models.BooleanField(default=False, verbose_name='c/ Cheddar'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l10_hellmanns',
            field=models.BooleanField(default=False, verbose_name='c/ Hellmanns'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l10_lanche',
            field=models.CharField(choices=[('----', '----'), ('X-Salada', 'X-Salada'), ('X-Duplo Salada', 'X-Duplo Salada'), ('X-Burger', 'X-Burger'), ('Frango', 'X-Frango'), ('X-Frango Bacon', 'X-Frango Bacon'), ('X-Frango Egg', 'X-Frango Egg'), ('X-Frango Bacon Egg', 'X-Frango Bacon Egg'), ('X-Egg', 'X-Egg'), ('X-Bacon', 'X-Bacon'), ('X-Bacon Egg', 'X-Bacon Egg'), ('Hot Dog', 'Hot Dog'), ('Dog Egg', 'Dog Egg'), ('Dog Bacon', 'Dog Bacon'), ('Dog Bacon Egg', 'Dog Bacon Egg'), ('X-Dogão', 'X-Dogão'), ('X-Calabresa', 'X-Calabresa'), ('X-Tudo', 'X-Tudo')], default='----', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l10_maionese',
            field=models.BooleanField(default=False, verbose_name='s/ Maionese'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l10_milho',
            field=models.BooleanField(default=False, verbose_name='s/ Milho'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l10_porcao',
            field=models.CharField(choices=[('----', '----'), ('Batata Meia', 'Batata Meia'), ('Batata Inteira', 'Batata Inteira'), ('Anel de Cebola', 'Anel de Cebola'), ('Frango', 'Fango'), ('Mini fritas', 'Mini fritas'), ('Especial', 'Especial')], default='----', max_length=20, verbose_name='Porção'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l10_pure',
            field=models.BooleanField(default=False, verbose_name='s/ Purê'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l10_quant_acai',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l10_quant_bebida',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l10_quant_lanche',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l10_quant_pocao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l10_tomate',
            field=models.BooleanField(default=False, verbose_name='s/ Tomate'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l10_total_acai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l10_total_bebida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l10_total_lanche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l10_total_porcao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l1_alface',
            field=models.BooleanField(default=False, verbose_name='s/ Alface'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l1_anel',
            field=models.BooleanField(default=False, verbose_name='c/ Anel de Cebola'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l1_bacon',
            field=models.BooleanField(default=False, verbose_name='c/ Bacon'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l1_catupiry',
            field=models.BooleanField(default=False, verbose_name='c/ Catupiry'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l1_cheddar',
            field=models.BooleanField(default=False, verbose_name='c/ Cheddar'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l1_hellmanns',
            field=models.BooleanField(default=False, verbose_name='c/ Hellmanns'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l1_maionese',
            field=models.BooleanField(default=False, verbose_name='s/ Maionese'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l1_milho',
            field=models.BooleanField(default=False, verbose_name='s/ Milho'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l1_pure',
            field=models.BooleanField(default=False, verbose_name='s/ Purê'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l1_tomate',
            field=models.BooleanField(default=False, verbose_name='s/ Tomate'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l2_acai',
            field=models.CharField(choices=[('----', '----'), ('400ml', '400ml'), ('500ml', '500ml'), ('700ml', '700ml')], default='----', max_length=30, verbose_name='Açaí'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l2_adicional_maionese',
            field=models.BooleanField(default=False, verbose_name='Adicional de Maionese'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l2_alface',
            field=models.BooleanField(default=False, verbose_name='s/ Alface'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l2_anel',
            field=models.BooleanField(default=False, verbose_name='c/ Anel de Cebola'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l2_bacon',
            field=models.BooleanField(default=False, verbose_name='c/ Bacon'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l2_bebida',
            field=models.CharField(choices=[('----', '----'), ('Refrigerante Lata', 'Refrigerante Lata'), ('Refrigerante 600', 'Refrigerante 600'), ('Refrigerante 1,5L', 'Refrigerante 1,5L'), ('Suco com água', 'Suco com água'), ('Suco com leite', 'Suco com leite')], default='----', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l2_catupiry',
            field=models.BooleanField(default=False, verbose_name='c/ Catupiry'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l2_cheddar',
            field=models.BooleanField(default=False, verbose_name='c/ Cheddar'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l2_hellmanns',
            field=models.BooleanField(default=False, verbose_name='c/ Hellmanns'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l2_lanche',
            field=models.CharField(choices=[('----', '----'), ('X-Salada', 'X-Salada'), ('X-Duplo Salada', 'X-Duplo Salada'), ('X-Burger', 'X-Burger'), ('Frango', 'X-Frango'), ('X-Frango Bacon', 'X-Frango Bacon'), ('X-Frango Egg', 'X-Frango Egg'), ('X-Frango Bacon Egg', 'X-Frango Bacon Egg'), ('X-Egg', 'X-Egg'), ('X-Bacon', 'X-Bacon'), ('X-Bacon Egg', 'X-Bacon Egg'), ('Hot Dog', 'Hot Dog'), ('Dog Egg', 'Dog Egg'), ('Dog Bacon', 'Dog Bacon'), ('Dog Bacon Egg', 'Dog Bacon Egg'), ('X-Dogão', 'X-Dogão'), ('X-Calabresa', 'X-Calabresa'), ('X-Tudo', 'X-Tudo')], default='----', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l2_maionese',
            field=models.BooleanField(default=False, verbose_name='s/ Maionese'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l2_milho',
            field=models.BooleanField(default=False, verbose_name='s/ Milho'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l2_porcao',
            field=models.CharField(choices=[('----', '----'), ('Batata Meia', 'Batata Meia'), ('Batata Inteira', 'Batata Inteira'), ('Anel de Cebola', 'Anel de Cebola'), ('Frango', 'Fango'), ('Mini fritas', 'Mini fritas'), ('Especial', 'Especial')], default='----', max_length=20, verbose_name='Porção'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l2_pure',
            field=models.BooleanField(default=False, verbose_name='s/ Purê'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l2_quant_acai',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l2_quant_bebida',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l2_quant_lanche',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l2_quant_pocao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l2_tomate',
            field=models.BooleanField(default=False, verbose_name='s/ Tomate'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l2_total_acai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l2_total_bebida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l2_total_lanche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l2_total_porcao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l3_acai',
            field=models.CharField(choices=[('----', '----'), ('400ml', '400ml'), ('500ml', '500ml'), ('700ml', '700ml')], default='----', max_length=30, verbose_name='Açaí'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l3_adicional_maionese',
            field=models.BooleanField(default=False, verbose_name='Adicional de Maionese'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l3_alface',
            field=models.BooleanField(default=False, verbose_name='s/ Alface'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l3_anel',
            field=models.BooleanField(default=False, verbose_name='c/ Anel de Cebola'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l3_bacon',
            field=models.BooleanField(default=False, verbose_name='c/ Bacon'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l3_bebida',
            field=models.CharField(choices=[('----', '----'), ('Refrigerante Lata', 'Refrigerante Lata'), ('Refrigerante 600', 'Refrigerante 600'), ('Refrigerante 1,5L', 'Refrigerante 1,5L'), ('Suco com água', 'Suco com água'), ('Suco com leite', 'Suco com leite')], default='----', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l3_catupiry',
            field=models.BooleanField(default=False, verbose_name='c/ Catupiry'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l3_cheddar',
            field=models.BooleanField(default=False, verbose_name='c/ Cheddar'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l3_hellmanns',
            field=models.BooleanField(default=False, verbose_name='c/ Hellmanns'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l3_lanche',
            field=models.CharField(choices=[('----', '----'), ('X-Salada', 'X-Salada'), ('X-Duplo Salada', 'X-Duplo Salada'), ('X-Burger', 'X-Burger'), ('Frango', 'X-Frango'), ('X-Frango Bacon', 'X-Frango Bacon'), ('X-Frango Egg', 'X-Frango Egg'), ('X-Frango Bacon Egg', 'X-Frango Bacon Egg'), ('X-Egg', 'X-Egg'), ('X-Bacon', 'X-Bacon'), ('X-Bacon Egg', 'X-Bacon Egg'), ('Hot Dog', 'Hot Dog'), ('Dog Egg', 'Dog Egg'), ('Dog Bacon', 'Dog Bacon'), ('Dog Bacon Egg', 'Dog Bacon Egg'), ('X-Dogão', 'X-Dogão'), ('X-Calabresa', 'X-Calabresa'), ('X-Tudo', 'X-Tudo')], default='----', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l3_maionese',
            field=models.BooleanField(default=False, verbose_name='s/ Maionese'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l3_milho',
            field=models.BooleanField(default=False, verbose_name='s/ Milho'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l3_porcao',
            field=models.CharField(choices=[('----', '----'), ('Batata Meia', 'Batata Meia'), ('Batata Inteira', 'Batata Inteira'), ('Anel de Cebola', 'Anel de Cebola'), ('Frango', 'Fango'), ('Mini fritas', 'Mini fritas'), ('Especial', 'Especial')], default='----', max_length=20, verbose_name='Porção'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l3_pure',
            field=models.BooleanField(default=False, verbose_name='s/ Purê'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l3_quant_acai',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l3_quant_bebida',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l3_quant_lanche',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l3_quant_pocao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l3_tomate',
            field=models.BooleanField(default=False, verbose_name='s/ Tomate'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l3_total_acai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l3_total_bebida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l3_total_lanche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l3_total_porcao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l4_acai',
            field=models.CharField(choices=[('----', '----'), ('400ml', '400ml'), ('500ml', '500ml'), ('700ml', '700ml')], default='----', max_length=30, verbose_name='Açaí'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l4_adicional_maionese',
            field=models.BooleanField(default=False, verbose_name='Adicional de Maionese'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l4_alface',
            field=models.BooleanField(default=False, verbose_name='s/ Alface'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l4_anel',
            field=models.BooleanField(default=False, verbose_name='c/ Anel de Cebola'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l4_bacon',
            field=models.BooleanField(default=False, verbose_name='c/ Bacon'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l4_bebida',
            field=models.CharField(choices=[('----', '----'), ('Refrigerante Lata', 'Refrigerante Lata'), ('Refrigerante 600', 'Refrigerante 600'), ('Refrigerante 1,5L', 'Refrigerante 1,5L'), ('Suco com água', 'Suco com água'), ('Suco com leite', 'Suco com leite')], default='----', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l4_catupiry',
            field=models.BooleanField(default=False, verbose_name='c/ Catupiry'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l4_cheddar',
            field=models.BooleanField(default=False, verbose_name='c/ Cheddar'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l4_hellmanns',
            field=models.BooleanField(default=False, verbose_name='c/ Hellmanns'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l4_lanche',
            field=models.CharField(choices=[('----', '----'), ('X-Salada', 'X-Salada'), ('X-Duplo Salada', 'X-Duplo Salada'), ('X-Burger', 'X-Burger'), ('Frango', 'X-Frango'), ('X-Frango Bacon', 'X-Frango Bacon'), ('X-Frango Egg', 'X-Frango Egg'), ('X-Frango Bacon Egg', 'X-Frango Bacon Egg'), ('X-Egg', 'X-Egg'), ('X-Bacon', 'X-Bacon'), ('X-Bacon Egg', 'X-Bacon Egg'), ('Hot Dog', 'Hot Dog'), ('Dog Egg', 'Dog Egg'), ('Dog Bacon', 'Dog Bacon'), ('Dog Bacon Egg', 'Dog Bacon Egg'), ('X-Dogão', 'X-Dogão'), ('X-Calabresa', 'X-Calabresa'), ('X-Tudo', 'X-Tudo')], default='----', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l4_maionese',
            field=models.BooleanField(default=False, verbose_name='s/ Maionese'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l4_milho',
            field=models.BooleanField(default=False, verbose_name='s/ Milho'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l4_porcao',
            field=models.CharField(choices=[('----', '----'), ('Batata Meia', 'Batata Meia'), ('Batata Inteira', 'Batata Inteira'), ('Anel de Cebola', 'Anel de Cebola'), ('Frango', 'Fango'), ('Mini fritas', 'Mini fritas'), ('Especial', 'Especial')], default='----', max_length=20, verbose_name='Porção'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l4_pure',
            field=models.BooleanField(default=False, verbose_name='s/ Purê'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l4_quant_acai',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l4_quant_bebida',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l4_quant_lanche',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l4_quant_pocao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l4_tomate',
            field=models.BooleanField(default=False, verbose_name='s/ Tomate'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l4_total_acai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l4_total_bebida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l4_total_lanche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l4_total_porcao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l5_acai',
            field=models.CharField(choices=[('----', '----'), ('400ml', '400ml'), ('500ml', '500ml'), ('700ml', '700ml')], default='----', max_length=30, verbose_name='Açaí'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l5_adicional_maionese',
            field=models.BooleanField(default=False, verbose_name='Adicional de Maionese'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l5_alface',
            field=models.BooleanField(default=False, verbose_name='s/ Alface'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l5_anel',
            field=models.BooleanField(default=False, verbose_name='c/ Anel de Cebola'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l5_bacon',
            field=models.BooleanField(default=False, verbose_name='c/ Bacon'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l5_bebida',
            field=models.CharField(choices=[('----', '----'), ('Refrigerante Lata', 'Refrigerante Lata'), ('Refrigerante 600', 'Refrigerante 600'), ('Refrigerante 1,5L', 'Refrigerante 1,5L'), ('Suco com água', 'Suco com água'), ('Suco com leite', 'Suco com leite')], default='----', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l5_catupiry',
            field=models.BooleanField(default=False, verbose_name='c/ Catupiry'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l5_cheddar',
            field=models.BooleanField(default=False, verbose_name='c/ Cheddar'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l5_hellmanns',
            field=models.BooleanField(default=False, verbose_name='c/ Hellmanns'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l5_lanche',
            field=models.CharField(choices=[('----', '----'), ('X-Salada', 'X-Salada'), ('X-Duplo Salada', 'X-Duplo Salada'), ('X-Burger', 'X-Burger'), ('Frango', 'X-Frango'), ('X-Frango Bacon', 'X-Frango Bacon'), ('X-Frango Egg', 'X-Frango Egg'), ('X-Frango Bacon Egg', 'X-Frango Bacon Egg'), ('X-Egg', 'X-Egg'), ('X-Bacon', 'X-Bacon'), ('X-Bacon Egg', 'X-Bacon Egg'), ('Hot Dog', 'Hot Dog'), ('Dog Egg', 'Dog Egg'), ('Dog Bacon', 'Dog Bacon'), ('Dog Bacon Egg', 'Dog Bacon Egg'), ('X-Dogão', 'X-Dogão'), ('X-Calabresa', 'X-Calabresa'), ('X-Tudo', 'X-Tudo')], default='----', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l5_maionese',
            field=models.BooleanField(default=False, verbose_name='s/ Maionese'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l5_milho',
            field=models.BooleanField(default=False, verbose_name='s/ Milho'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l5_porcao',
            field=models.CharField(choices=[('----', '----'), ('Batata Meia', 'Batata Meia'), ('Batata Inteira', 'Batata Inteira'), ('Anel de Cebola', 'Anel de Cebola'), ('Frango', 'Fango'), ('Mini fritas', 'Mini fritas'), ('Especial', 'Especial')], default='----', max_length=20, verbose_name='Porção'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l5_pure',
            field=models.BooleanField(default=False, verbose_name='s/ Purê'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l5_quant_acai',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l5_quant_bebida',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l5_quant_lanche',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l5_quant_pocao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l5_tomate',
            field=models.BooleanField(default=False, verbose_name='s/ Tomate'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l5_total_acai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l5_total_bebida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l5_total_lanche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l5_total_porcao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l6_acai',
            field=models.CharField(choices=[('----', '----'), ('400ml', '400ml'), ('500ml', '500ml'), ('700ml', '700ml')], default='----', max_length=30, verbose_name='Açaí'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l6_adicional_maionese',
            field=models.BooleanField(default=False, verbose_name='Adicional de Maionese'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l6_alface',
            field=models.BooleanField(default=False, verbose_name='s/ Alface'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l6_anel',
            field=models.BooleanField(default=False, verbose_name='c/ Anel de Cebola'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l6_bacon',
            field=models.BooleanField(default=False, verbose_name='c/ Bacon'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l6_bebida',
            field=models.CharField(choices=[('----', '----'), ('Refrigerante Lata', 'Refrigerante Lata'), ('Refrigerante 600', 'Refrigerante 600'), ('Refrigerante 1,5L', 'Refrigerante 1,5L'), ('Suco com água', 'Suco com água'), ('Suco com leite', 'Suco com leite')], default='----', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l6_catupiry',
            field=models.BooleanField(default=False, verbose_name='c/ Catupiry'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l6_cheddar',
            field=models.BooleanField(default=False, verbose_name='c/ Cheddar'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l6_hellmanns',
            field=models.BooleanField(default=False, verbose_name='c/ Hellmanns'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l6_lanche',
            field=models.CharField(choices=[('----', '----'), ('X-Salada', 'X-Salada'), ('X-Duplo Salada', 'X-Duplo Salada'), ('X-Burger', 'X-Burger'), ('Frango', 'X-Frango'), ('X-Frango Bacon', 'X-Frango Bacon'), ('X-Frango Egg', 'X-Frango Egg'), ('X-Frango Bacon Egg', 'X-Frango Bacon Egg'), ('X-Egg', 'X-Egg'), ('X-Bacon', 'X-Bacon'), ('X-Bacon Egg', 'X-Bacon Egg'), ('Hot Dog', 'Hot Dog'), ('Dog Egg', 'Dog Egg'), ('Dog Bacon', 'Dog Bacon'), ('Dog Bacon Egg', 'Dog Bacon Egg'), ('X-Dogão', 'X-Dogão'), ('X-Calabresa', 'X-Calabresa'), ('X-Tudo', 'X-Tudo')], default='----', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l6_maionese',
            field=models.BooleanField(default=False, verbose_name='s/ Maionese'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l6_milho',
            field=models.BooleanField(default=False, verbose_name='s/ Milho'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l6_porcao',
            field=models.CharField(choices=[('----', '----'), ('Batata Meia', 'Batata Meia'), ('Batata Inteira', 'Batata Inteira'), ('Anel de Cebola', 'Anel de Cebola'), ('Frango', 'Fango'), ('Mini fritas', 'Mini fritas'), ('Especial', 'Especial')], default='----', max_length=20, verbose_name='Porção'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l6_pure',
            field=models.BooleanField(default=False, verbose_name='s/ Purê'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l6_quant_acai',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l6_quant_bebida',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l6_quant_lanche',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l6_quant_pocao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l6_tomate',
            field=models.BooleanField(default=False, verbose_name='s/ Tomate'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l6_total_acai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l6_total_bebida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l6_total_lanche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l6_total_porcao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l7_acai',
            field=models.CharField(choices=[('----', '----'), ('400ml', '400ml'), ('500ml', '500ml'), ('700ml', '700ml')], default='----', max_length=30, verbose_name='Açaí'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l7_adicional_maionese',
            field=models.BooleanField(default=False, verbose_name='Adicional de Maionese'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l7_alface',
            field=models.BooleanField(default=False, verbose_name='s/ Alface'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l7_anel',
            field=models.BooleanField(default=False, verbose_name='c/ Anel de Cebola'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l7_bacon',
            field=models.BooleanField(default=False, verbose_name='c/ Bacon'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l7_bebida',
            field=models.CharField(choices=[('----', '----'), ('Refrigerante Lata', 'Refrigerante Lata'), ('Refrigerante 600', 'Refrigerante 600'), ('Refrigerante 1,5L', 'Refrigerante 1,5L'), ('Suco com água', 'Suco com água'), ('Suco com leite', 'Suco com leite')], default='----', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l7_catupiry',
            field=models.BooleanField(default=False, verbose_name='c/ Catupiry'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l7_cheddar',
            field=models.BooleanField(default=False, verbose_name='c/ Cheddar'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l7_hellmanns',
            field=models.BooleanField(default=False, verbose_name='c/ Hellmanns'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l7_lanche',
            field=models.CharField(choices=[('----', '----'), ('X-Salada', 'X-Salada'), ('X-Duplo Salada', 'X-Duplo Salada'), ('X-Burger', 'X-Burger'), ('Frango', 'X-Frango'), ('X-Frango Bacon', 'X-Frango Bacon'), ('X-Frango Egg', 'X-Frango Egg'), ('X-Frango Bacon Egg', 'X-Frango Bacon Egg'), ('X-Egg', 'X-Egg'), ('X-Bacon', 'X-Bacon'), ('X-Bacon Egg', 'X-Bacon Egg'), ('Hot Dog', 'Hot Dog'), ('Dog Egg', 'Dog Egg'), ('Dog Bacon', 'Dog Bacon'), ('Dog Bacon Egg', 'Dog Bacon Egg'), ('X-Dogão', 'X-Dogão'), ('X-Calabresa', 'X-Calabresa'), ('X-Tudo', 'X-Tudo')], default='----', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l7_maionese',
            field=models.BooleanField(default=False, verbose_name='s/ Maionese'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l7_milho',
            field=models.BooleanField(default=False, verbose_name='s/ Milho'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l7_porcao',
            field=models.CharField(choices=[('----', '----'), ('Batata Meia', 'Batata Meia'), ('Batata Inteira', 'Batata Inteira'), ('Anel de Cebola', 'Anel de Cebola'), ('Frango', 'Fango'), ('Mini fritas', 'Mini fritas'), ('Especial', 'Especial')], default='----', max_length=20, verbose_name='Porção'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l7_pure',
            field=models.BooleanField(default=False, verbose_name='s/ Purê'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l7_quant_acai',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l7_quant_bebida',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l7_quant_lanche',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l7_quant_pocao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l7_tomate',
            field=models.BooleanField(default=False, verbose_name='s/ Tomate'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l7_total_acai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l7_total_bebida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l7_total_lanche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l7_total_porcao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l8_acai',
            field=models.CharField(choices=[('----', '----'), ('400ml', '400ml'), ('500ml', '500ml'), ('700ml', '700ml')], default='----', max_length=30, verbose_name='Açaí'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l8_adicional_maionese',
            field=models.BooleanField(default=False, verbose_name='Adicional de Maionese'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l8_alface',
            field=models.BooleanField(default=False, verbose_name='s/ Alface'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l8_anel',
            field=models.BooleanField(default=False, verbose_name='c/ Anel de Cebola'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l8_bacon',
            field=models.BooleanField(default=False, verbose_name='c/ Bacon'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l8_bebida',
            field=models.CharField(choices=[('----', '----'), ('Refrigerante Lata', 'Refrigerante Lata'), ('Refrigerante 600', 'Refrigerante 600'), ('Refrigerante 1,5L', 'Refrigerante 1,5L'), ('Suco com água', 'Suco com água'), ('Suco com leite', 'Suco com leite')], default='----', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l8_catupiry',
            field=models.BooleanField(default=False, verbose_name='c/ Catupiry'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l8_cheddar',
            field=models.BooleanField(default=False, verbose_name='c/ Cheddar'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l8_hellmanns',
            field=models.BooleanField(default=False, verbose_name='c/ Hellmanns'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l8_lanche',
            field=models.CharField(choices=[('----', '----'), ('X-Salada', 'X-Salada'), ('X-Duplo Salada', 'X-Duplo Salada'), ('X-Burger', 'X-Burger'), ('Frango', 'X-Frango'), ('X-Frango Bacon', 'X-Frango Bacon'), ('X-Frango Egg', 'X-Frango Egg'), ('X-Frango Bacon Egg', 'X-Frango Bacon Egg'), ('X-Egg', 'X-Egg'), ('X-Bacon', 'X-Bacon'), ('X-Bacon Egg', 'X-Bacon Egg'), ('Hot Dog', 'Hot Dog'), ('Dog Egg', 'Dog Egg'), ('Dog Bacon', 'Dog Bacon'), ('Dog Bacon Egg', 'Dog Bacon Egg'), ('X-Dogão', 'X-Dogão'), ('X-Calabresa', 'X-Calabresa'), ('X-Tudo', 'X-Tudo')], default='----', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l8_maionese',
            field=models.BooleanField(default=False, verbose_name='s/ Maionese'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l8_milho',
            field=models.BooleanField(default=False, verbose_name='s/ Milho'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l8_porcao',
            field=models.CharField(choices=[('----', '----'), ('Batata Meia', 'Batata Meia'), ('Batata Inteira', 'Batata Inteira'), ('Anel de Cebola', 'Anel de Cebola'), ('Frango', 'Fango'), ('Mini fritas', 'Mini fritas'), ('Especial', 'Especial')], default='----', max_length=20, verbose_name='Porção'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l8_pure',
            field=models.BooleanField(default=False, verbose_name='s/ Purê'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l8_quant_acai',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l8_quant_bebida',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l8_quant_lanche',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l8_quant_pocao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l8_tomate',
            field=models.BooleanField(default=False, verbose_name='s/ Tomate'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l8_total_acai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l8_total_bebida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l8_total_lanche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l8_total_porcao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l9_acai',
            field=models.CharField(choices=[('----', '----'), ('400ml', '400ml'), ('500ml', '500ml'), ('700ml', '700ml')], default='----', max_length=30, verbose_name='Açaí'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l9_adicional_maionese',
            field=models.BooleanField(default=False, verbose_name='Adicional de Maionese'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l9_alface',
            field=models.BooleanField(default=False, verbose_name='s/ Alface'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l9_anel',
            field=models.BooleanField(default=False, verbose_name='c/ Anel de Cebola'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l9_bacon',
            field=models.BooleanField(default=False, verbose_name='c/ Bacon'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l9_bebida',
            field=models.CharField(choices=[('----', '----'), ('Refrigerante Lata', 'Refrigerante Lata'), ('Refrigerante 600', 'Refrigerante 600'), ('Refrigerante 1,5L', 'Refrigerante 1,5L'), ('Suco com água', 'Suco com água'), ('Suco com leite', 'Suco com leite')], default='----', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l9_catupiry',
            field=models.BooleanField(default=False, verbose_name='c/ Catupiry'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l9_cheddar',
            field=models.BooleanField(default=False, verbose_name='c/ Cheddar'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l9_hellmanns',
            field=models.BooleanField(default=False, verbose_name='c/ Hellmanns'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l9_lanche',
            field=models.CharField(choices=[('----', '----'), ('X-Salada', 'X-Salada'), ('X-Duplo Salada', 'X-Duplo Salada'), ('X-Burger', 'X-Burger'), ('Frango', 'X-Frango'), ('X-Frango Bacon', 'X-Frango Bacon'), ('X-Frango Egg', 'X-Frango Egg'), ('X-Frango Bacon Egg', 'X-Frango Bacon Egg'), ('X-Egg', 'X-Egg'), ('X-Bacon', 'X-Bacon'), ('X-Bacon Egg', 'X-Bacon Egg'), ('Hot Dog', 'Hot Dog'), ('Dog Egg', 'Dog Egg'), ('Dog Bacon', 'Dog Bacon'), ('Dog Bacon Egg', 'Dog Bacon Egg'), ('X-Dogão', 'X-Dogão'), ('X-Calabresa', 'X-Calabresa'), ('X-Tudo', 'X-Tudo')], default='----', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l9_maionese',
            field=models.BooleanField(default=False, verbose_name='s/ Maionese'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l9_milho',
            field=models.BooleanField(default=False, verbose_name='s/ Milho'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l9_porcao',
            field=models.CharField(choices=[('----', '----'), ('Batata Meia', 'Batata Meia'), ('Batata Inteira', 'Batata Inteira'), ('Anel de Cebola', 'Anel de Cebola'), ('Frango', 'Fango'), ('Mini fritas', 'Mini fritas'), ('Especial', 'Especial')], default='----', max_length=20, verbose_name='Porção'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l9_pure',
            field=models.BooleanField(default=False, verbose_name='s/ Purê'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l9_quant_acai',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l9_quant_bebida',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l9_quant_lanche',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l9_quant_pocao',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l9_tomate',
            field=models.BooleanField(default=False, verbose_name='s/ Tomate'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l9_total_acai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l9_total_bebida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l9_total_lanche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l9_total_porcao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
