# Generated by Django 4.0 on 2022-01-04 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_rename_acai_pedido_l1_acai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='l10_preco_acai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l10_preco_bebida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l10_preco_lanche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l10_preco_pocao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l1_preco_acai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l1_preco_bebida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l1_preco_lanche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l1_preco_pocao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l2_preco_acai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l2_preco_bebida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l2_preco_lanche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l2_preco_pocao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l3_preco_acai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l3_preco_bebida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l3_preco_lanche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l3_preco_pocao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l4_preco_acai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l4_preco_bebida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l4_preco_lanche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l4_preco_pocao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l5_preco_acai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l5_preco_bebida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l5_preco_lanche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l5_preco_pocao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l6_preco_acai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l6_preco_bebida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l6_preco_lanche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l6_preco_pocao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l7_preco_acai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l7_preco_bebida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l7_preco_lanche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l7_preco_pocao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l8_preco_acai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l8_preco_bebida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l8_preco_lanche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l8_preco_pocao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l9_preco_acai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l9_preco_bebida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l9_preco_lanche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l9_preco_pocao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l10_bebida',
            field=models.CharField(choices=[('----', '----'), ('Refrigerante Lata', 'Refrigerante Lata'), ('Refrigerante 600', 'Refrigerante 600'), ('Refrigerante 1,5L', 'Refrigerante 1,5L'), ('Suco com água', 'Suco com água'), ('Suco com leite', 'Suco com leite')], default='----', max_length=20, verbose_name='Bebida'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l10_lanche',
            field=models.CharField(choices=[('----', '----'), ('X-Salada', 'X-Salada'), ('X-Duplo Salada', 'X-Duplo Salada'), ('X-Burger', 'X-Burger'), ('Frango', 'X-Frango'), ('X-Frango Bacon', 'X-Frango Bacon'), ('X-Frango Egg', 'X-Frango Egg'), ('X-Frango Bacon Egg', 'X-Frango Bacon Egg'), ('X-Egg', 'X-Egg'), ('X-Bacon', 'X-Bacon'), ('X-Bacon Egg', 'X-Bacon Egg'), ('Hot Dog', 'Hot Dog'), ('Dog Egg', 'Dog Egg'), ('Dog Bacon', 'Dog Bacon'), ('Dog Bacon Egg', 'Dog Bacon Egg'), ('X-Dogão', 'X-Dogão'), ('X-Calabresa', 'X-Calabresa'), ('X-Tudo', 'X-Tudo')], default='----', max_length=20, verbose_name='Lanche'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l10_quant_acai',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l10_quant_bebida',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l10_quant_lanche',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l10_quant_pocao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l10_total_acai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l10_total_bebida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l10_total_lanche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l10_total_porcao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l1_bebida',
            field=models.CharField(choices=[('----', '----'), ('Refrigerante Lata', 'Refrigerante Lata'), ('Refrigerante 600', 'Refrigerante 600'), ('Refrigerante 1,5L', 'Refrigerante 1,5L'), ('Suco com água', 'Suco com água'), ('Suco com leite', 'Suco com leite')], default='----', max_length=20, verbose_name='Bebida'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l1_lanche',
            field=models.CharField(choices=[('----', '----'), ('X-Salada', 'X-Salada'), ('X-Duplo Salada', 'X-Duplo Salada'), ('X-Burger', 'X-Burger'), ('Frango', 'X-Frango'), ('X-Frango Bacon', 'X-Frango Bacon'), ('X-Frango Egg', 'X-Frango Egg'), ('X-Frango Bacon Egg', 'X-Frango Bacon Egg'), ('X-Egg', 'X-Egg'), ('X-Bacon', 'X-Bacon'), ('X-Bacon Egg', 'X-Bacon Egg'), ('Hot Dog', 'Hot Dog'), ('Dog Egg', 'Dog Egg'), ('Dog Bacon', 'Dog Bacon'), ('Dog Bacon Egg', 'Dog Bacon Egg'), ('X-Dogão', 'X-Dogão'), ('X-Calabresa', 'X-Calabresa'), ('X-Tudo', 'X-Tudo')], default='----', max_length=20, verbose_name='Lanche'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l1_quant_acai',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l1_quant_bebida',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l1_quant_lanche',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l1_quant_pocao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l1_total_acai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l1_total_bebida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l1_total_lanche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l1_total_porcao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l2_bebida',
            field=models.CharField(choices=[('----', '----'), ('Refrigerante Lata', 'Refrigerante Lata'), ('Refrigerante 600', 'Refrigerante 600'), ('Refrigerante 1,5L', 'Refrigerante 1,5L'), ('Suco com água', 'Suco com água'), ('Suco com leite', 'Suco com leite')], default='----', max_length=20, verbose_name='Bebida'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l2_lanche',
            field=models.CharField(choices=[('----', '----'), ('X-Salada', 'X-Salada'), ('X-Duplo Salada', 'X-Duplo Salada'), ('X-Burger', 'X-Burger'), ('Frango', 'X-Frango'), ('X-Frango Bacon', 'X-Frango Bacon'), ('X-Frango Egg', 'X-Frango Egg'), ('X-Frango Bacon Egg', 'X-Frango Bacon Egg'), ('X-Egg', 'X-Egg'), ('X-Bacon', 'X-Bacon'), ('X-Bacon Egg', 'X-Bacon Egg'), ('Hot Dog', 'Hot Dog'), ('Dog Egg', 'Dog Egg'), ('Dog Bacon', 'Dog Bacon'), ('Dog Bacon Egg', 'Dog Bacon Egg'), ('X-Dogão', 'X-Dogão'), ('X-Calabresa', 'X-Calabresa'), ('X-Tudo', 'X-Tudo')], default='----', max_length=20, verbose_name='Lanche'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l2_quant_acai',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l2_quant_bebida',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l2_quant_lanche',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l2_quant_pocao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l2_total_acai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l2_total_bebida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l2_total_lanche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l2_total_porcao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l3_bebida',
            field=models.CharField(choices=[('----', '----'), ('Refrigerante Lata', 'Refrigerante Lata'), ('Refrigerante 600', 'Refrigerante 600'), ('Refrigerante 1,5L', 'Refrigerante 1,5L'), ('Suco com água', 'Suco com água'), ('Suco com leite', 'Suco com leite')], default='----', max_length=20, verbose_name='Bebida'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l3_lanche',
            field=models.CharField(choices=[('----', '----'), ('X-Salada', 'X-Salada'), ('X-Duplo Salada', 'X-Duplo Salada'), ('X-Burger', 'X-Burger'), ('Frango', 'X-Frango'), ('X-Frango Bacon', 'X-Frango Bacon'), ('X-Frango Egg', 'X-Frango Egg'), ('X-Frango Bacon Egg', 'X-Frango Bacon Egg'), ('X-Egg', 'X-Egg'), ('X-Bacon', 'X-Bacon'), ('X-Bacon Egg', 'X-Bacon Egg'), ('Hot Dog', 'Hot Dog'), ('Dog Egg', 'Dog Egg'), ('Dog Bacon', 'Dog Bacon'), ('Dog Bacon Egg', 'Dog Bacon Egg'), ('X-Dogão', 'X-Dogão'), ('X-Calabresa', 'X-Calabresa'), ('X-Tudo', 'X-Tudo')], default='----', max_length=20, verbose_name='Lanche'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l3_quant_acai',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l3_quant_bebida',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l3_quant_lanche',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l3_quant_pocao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l3_total_acai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l3_total_bebida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l3_total_lanche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l3_total_porcao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l4_bebida',
            field=models.CharField(choices=[('----', '----'), ('Refrigerante Lata', 'Refrigerante Lata'), ('Refrigerante 600', 'Refrigerante 600'), ('Refrigerante 1,5L', 'Refrigerante 1,5L'), ('Suco com água', 'Suco com água'), ('Suco com leite', 'Suco com leite')], default='----', max_length=20, verbose_name='Bebida'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l4_lanche',
            field=models.CharField(choices=[('----', '----'), ('X-Salada', 'X-Salada'), ('X-Duplo Salada', 'X-Duplo Salada'), ('X-Burger', 'X-Burger'), ('Frango', 'X-Frango'), ('X-Frango Bacon', 'X-Frango Bacon'), ('X-Frango Egg', 'X-Frango Egg'), ('X-Frango Bacon Egg', 'X-Frango Bacon Egg'), ('X-Egg', 'X-Egg'), ('X-Bacon', 'X-Bacon'), ('X-Bacon Egg', 'X-Bacon Egg'), ('Hot Dog', 'Hot Dog'), ('Dog Egg', 'Dog Egg'), ('Dog Bacon', 'Dog Bacon'), ('Dog Bacon Egg', 'Dog Bacon Egg'), ('X-Dogão', 'X-Dogão'), ('X-Calabresa', 'X-Calabresa'), ('X-Tudo', 'X-Tudo')], default='----', max_length=20, verbose_name='Lanche'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l4_quant_acai',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l4_quant_bebida',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l4_quant_lanche',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l4_quant_pocao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l4_total_acai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l4_total_bebida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l4_total_lanche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l4_total_porcao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l5_bebida',
            field=models.CharField(choices=[('----', '----'), ('Refrigerante Lata', 'Refrigerante Lata'), ('Refrigerante 600', 'Refrigerante 600'), ('Refrigerante 1,5L', 'Refrigerante 1,5L'), ('Suco com água', 'Suco com água'), ('Suco com leite', 'Suco com leite')], default='----', max_length=20, verbose_name='Bebida'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l5_lanche',
            field=models.CharField(choices=[('----', '----'), ('X-Salada', 'X-Salada'), ('X-Duplo Salada', 'X-Duplo Salada'), ('X-Burger', 'X-Burger'), ('Frango', 'X-Frango'), ('X-Frango Bacon', 'X-Frango Bacon'), ('X-Frango Egg', 'X-Frango Egg'), ('X-Frango Bacon Egg', 'X-Frango Bacon Egg'), ('X-Egg', 'X-Egg'), ('X-Bacon', 'X-Bacon'), ('X-Bacon Egg', 'X-Bacon Egg'), ('Hot Dog', 'Hot Dog'), ('Dog Egg', 'Dog Egg'), ('Dog Bacon', 'Dog Bacon'), ('Dog Bacon Egg', 'Dog Bacon Egg'), ('X-Dogão', 'X-Dogão'), ('X-Calabresa', 'X-Calabresa'), ('X-Tudo', 'X-Tudo')], default='----', max_length=20, verbose_name='Lanche'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l5_quant_acai',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l5_quant_bebida',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l5_quant_lanche',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l5_quant_pocao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l5_total_acai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l5_total_bebida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l5_total_lanche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l5_total_porcao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l6_bebida',
            field=models.CharField(choices=[('----', '----'), ('Refrigerante Lata', 'Refrigerante Lata'), ('Refrigerante 600', 'Refrigerante 600'), ('Refrigerante 1,5L', 'Refrigerante 1,5L'), ('Suco com água', 'Suco com água'), ('Suco com leite', 'Suco com leite')], default='----', max_length=20, verbose_name='Bebida'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l6_lanche',
            field=models.CharField(choices=[('----', '----'), ('X-Salada', 'X-Salada'), ('X-Duplo Salada', 'X-Duplo Salada'), ('X-Burger', 'X-Burger'), ('Frango', 'X-Frango'), ('X-Frango Bacon', 'X-Frango Bacon'), ('X-Frango Egg', 'X-Frango Egg'), ('X-Frango Bacon Egg', 'X-Frango Bacon Egg'), ('X-Egg', 'X-Egg'), ('X-Bacon', 'X-Bacon'), ('X-Bacon Egg', 'X-Bacon Egg'), ('Hot Dog', 'Hot Dog'), ('Dog Egg', 'Dog Egg'), ('Dog Bacon', 'Dog Bacon'), ('Dog Bacon Egg', 'Dog Bacon Egg'), ('X-Dogão', 'X-Dogão'), ('X-Calabresa', 'X-Calabresa'), ('X-Tudo', 'X-Tudo')], default='----', max_length=20, verbose_name='Lanche'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l6_quant_acai',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l6_quant_bebida',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l6_quant_lanche',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l6_quant_pocao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l6_total_acai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l6_total_bebida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l6_total_lanche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l6_total_porcao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l7_bebida',
            field=models.CharField(choices=[('----', '----'), ('Refrigerante Lata', 'Refrigerante Lata'), ('Refrigerante 600', 'Refrigerante 600'), ('Refrigerante 1,5L', 'Refrigerante 1,5L'), ('Suco com água', 'Suco com água'), ('Suco com leite', 'Suco com leite')], default='----', max_length=20, verbose_name='Bebida'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l7_lanche',
            field=models.CharField(choices=[('----', '----'), ('X-Salada', 'X-Salada'), ('X-Duplo Salada', 'X-Duplo Salada'), ('X-Burger', 'X-Burger'), ('Frango', 'X-Frango'), ('X-Frango Bacon', 'X-Frango Bacon'), ('X-Frango Egg', 'X-Frango Egg'), ('X-Frango Bacon Egg', 'X-Frango Bacon Egg'), ('X-Egg', 'X-Egg'), ('X-Bacon', 'X-Bacon'), ('X-Bacon Egg', 'X-Bacon Egg'), ('Hot Dog', 'Hot Dog'), ('Dog Egg', 'Dog Egg'), ('Dog Bacon', 'Dog Bacon'), ('Dog Bacon Egg', 'Dog Bacon Egg'), ('X-Dogão', 'X-Dogão'), ('X-Calabresa', 'X-Calabresa'), ('X-Tudo', 'X-Tudo')], default='----', max_length=20, verbose_name='Lanche'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l7_quant_acai',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l7_quant_bebida',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l7_quant_lanche',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l7_quant_pocao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l7_total_acai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l7_total_bebida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l7_total_lanche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l7_total_porcao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l8_bebida',
            field=models.CharField(choices=[('----', '----'), ('Refrigerante Lata', 'Refrigerante Lata'), ('Refrigerante 600', 'Refrigerante 600'), ('Refrigerante 1,5L', 'Refrigerante 1,5L'), ('Suco com água', 'Suco com água'), ('Suco com leite', 'Suco com leite')], default='----', max_length=20, verbose_name='Bebida'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l8_lanche',
            field=models.CharField(choices=[('----', '----'), ('X-Salada', 'X-Salada'), ('X-Duplo Salada', 'X-Duplo Salada'), ('X-Burger', 'X-Burger'), ('Frango', 'X-Frango'), ('X-Frango Bacon', 'X-Frango Bacon'), ('X-Frango Egg', 'X-Frango Egg'), ('X-Frango Bacon Egg', 'X-Frango Bacon Egg'), ('X-Egg', 'X-Egg'), ('X-Bacon', 'X-Bacon'), ('X-Bacon Egg', 'X-Bacon Egg'), ('Hot Dog', 'Hot Dog'), ('Dog Egg', 'Dog Egg'), ('Dog Bacon', 'Dog Bacon'), ('Dog Bacon Egg', 'Dog Bacon Egg'), ('X-Dogão', 'X-Dogão'), ('X-Calabresa', 'X-Calabresa'), ('X-Tudo', 'X-Tudo')], default='----', max_length=20, verbose_name='Lanche'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l8_quant_acai',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l8_quant_bebida',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l8_quant_lanche',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l8_quant_pocao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l8_total_acai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l8_total_bebida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l8_total_lanche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l8_total_porcao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l9_bebida',
            field=models.CharField(choices=[('----', '----'), ('Refrigerante Lata', 'Refrigerante Lata'), ('Refrigerante 600', 'Refrigerante 600'), ('Refrigerante 1,5L', 'Refrigerante 1,5L'), ('Suco com água', 'Suco com água'), ('Suco com leite', 'Suco com leite')], default='----', max_length=20, verbose_name='Bebida'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l9_lanche',
            field=models.CharField(choices=[('----', '----'), ('X-Salada', 'X-Salada'), ('X-Duplo Salada', 'X-Duplo Salada'), ('X-Burger', 'X-Burger'), ('Frango', 'X-Frango'), ('X-Frango Bacon', 'X-Frango Bacon'), ('X-Frango Egg', 'X-Frango Egg'), ('X-Frango Bacon Egg', 'X-Frango Bacon Egg'), ('X-Egg', 'X-Egg'), ('X-Bacon', 'X-Bacon'), ('X-Bacon Egg', 'X-Bacon Egg'), ('Hot Dog', 'Hot Dog'), ('Dog Egg', 'Dog Egg'), ('Dog Bacon', 'Dog Bacon'), ('Dog Bacon Egg', 'Dog Bacon Egg'), ('X-Dogão', 'X-Dogão'), ('X-Calabresa', 'X-Calabresa'), ('X-Tudo', 'X-Tudo')], default='----', max_length=20, verbose_name='Lanche'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l9_quant_acai',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l9_quant_bebida',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l9_quant_lanche',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l9_quant_pocao',
            field=models.IntegerField(blank=True, null=True, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l9_total_acai',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l9_total_bebida',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l9_total_lanche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='l9_total_porcao',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Total'),
        ),
    ]
