# Generated by Django 4.0 on 2022-01-04 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_pedido_l10_preco_acai_pedido_l10_preco_bebida_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='l10_preco_pocao',
            new_name='l10_preco_porcao',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='l10_quant_pocao',
            new_name='l10_quant_porcao',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='l1_preco_pocao',
            new_name='l1_preco_porcao',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='l1_quant_pocao',
            new_name='l1_quant_porcao',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='l2_preco_pocao',
            new_name='l2_preco_porcao',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='l2_quant_pocao',
            new_name='l2_quant_porcao',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='l3_preco_pocao',
            new_name='l3_preco_porcao',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='l3_quant_pocao',
            new_name='l3_quant_porcao',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='l4_preco_pocao',
            new_name='l4_preco_porcao',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='l4_quant_pocao',
            new_name='l4_quant_porcao',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='l5_preco_pocao',
            new_name='l5_preco_porcao',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='l5_quant_pocao',
            new_name='l5_quant_porcao',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='l6_preco_pocao',
            new_name='l6_preco_porcao',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='l6_quant_pocao',
            new_name='l6_quant_porcao',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='l7_preco_pocao',
            new_name='l7_preco_porcao',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='l7_quant_pocao',
            new_name='l7_quant_porcao',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='l8_preco_pocao',
            new_name='l8_preco_porcao',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='l8_quant_pocao',
            new_name='l8_quant_porcao',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='l9_preco_pocao',
            new_name='l9_preco_porcao',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='l9_quant_pocao',
            new_name='l9_quant_porcao',
        ),
    ]
