# Generated by Django 4.0 on 2022-01-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0004_rename_l10_preco_pocao_pedido_l10_preco_porcao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='l10_cheddarp',
            field=models.BooleanField(default=False, verbose_name='c/ Cheddar'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l1_cheddarp',
            field=models.BooleanField(default=False, verbose_name='c/ Cheddar'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l2_cheddarp',
            field=models.BooleanField(default=False, verbose_name='c/ Cheddar'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l3_cheddarp',
            field=models.BooleanField(default=False, verbose_name='c/ Cheddar'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l4_cheddarp',
            field=models.BooleanField(default=False, verbose_name='c/ Cheddar'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l5_cheddarp',
            field=models.BooleanField(default=False, verbose_name='c/ Cheddar'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l6_cheddarp',
            field=models.BooleanField(default=False, verbose_name='c/ Cheddar'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l7_cheddarp',
            field=models.BooleanField(default=False, verbose_name='c/ Cheddar'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l8_cheddarp',
            field=models.BooleanField(default=False, verbose_name='c/ Cheddar'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='l9_cheddarp',
            field=models.BooleanField(default=False, verbose_name='c/ Cheddar'),
        ),
    ]
